language: groovy
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

install:
 - ./gradlew clean

script:
 - ./gradlew -S -i check gradleTest assemble

jdk:
 - oraclejdk8
 - openjdk7

os:
 - linux

env: TERM=dumb

cache:
  directories:
    - $HOME/.gradle
